dist: bionic

language: python

cache: pip

# Only run on main (still tests PRs)
branches:
  only:
  - main
  - /v\d+.\d+.\d+/

notifications:
  email: true

matrix:
  include:
    - python: '3.9'
    - python: '3.10'
    - python: '3.11'
    - python: '3.12'
    - python: '3.13'

install:
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
- pip install setuptools=="60.8.2"

script:
- make ci