dist: bionic

language: python
python:
  - "3.11"

cache: pip

# Only run on main (still tests PRs)
branches:
  only:
  - main

notifications:
  email: true

before_install:
# create an .env file that is pulled in while executing the v2 integration tests
- echo "CODE_ENGINE_URL=https://$CE_API_HOST/v2" > code_engine_v2.env
- echo "CODE_ENGINE_AUTH_TYPE=iam" >> code_engine_v2.env
- echo "CODE_ENGINE_APIKEY=$CE_API_KEY" >> code_engine_v2.env
- echo "CODE_ENGINE_AUTH_URL=$IAM_ENDPOINT" >> code_engine_v2.env

install:
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
- pip install setuptools=="60.8.2"

script:
- make ci
- make test-int

before_deploy:
- nvm install 14
- npm install
- pip install bump2version

deploy:
# Use semantic release to create a tag and release on each commit to the main branch
- provider: script
  script: npm run semantic-release
  skip_cleanup: true
  on:
    branch: main