dist: bionic

language: python

cache: pip

# Only run on main (still tests PRs)
branches:
  only:
  - main
  - /v\d+.\d+.\d+/

notifications:
  email: true

matrix:
  include:
    - python: '3.7'
    - python: '3.8'
    - python: '3.9'
    - python: '3.10'

install:
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc
- echo -e "machine github.ibm.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
- pip install setuptools=="60.8.2"

script:
- make ci

deploy:
- provider: pypi
  user: __token__
  password:
    secure: lUZvqL7OY4b6JsZ3w8lbRzx3e1xPGdCaV2eXTZ/fTy+soRWSe8PayK8YkC9oNa9SuNDpJ1n2w24sq24O2KMsjhw7mpJHLPOR9Yj2hVlWL1GSvAT3huI0j4PnBc6LAGXqtFBF2YYr4mIFNV5Zx8WJ0GOT4JNZIaH7M1HrnK224aOkUFNaZXP/a0bwBI9uWFKPLbRoggoYtKU1z7SM18+OINSZOSPzHIyl6ng41pdEWLsdkP+3zt29+LbARMIsocOJ6tLXeM6Dn8G5IxZ9pvJk+royo4MTIKJ1k7QN5s2x19mZoM6SrC/loxSfAFjgypxRDlXK43OWOMRrKnfj7RVl5fW3TIi1RoAq6T6ciC8Yv80ZUr6tIMcBWGkpi7Pbfsc1Z9toYeoGwdc8VSgnl97+Oj8M4WsT03Wc9/Gnlr0MGG1jzUoCH58HjK0ATIP1r5g+KBSHWyJtksonnPXk/JepQQPxDCa6zB2vZz7MnAXTc3hg+6rWpxjy+RpIkmLq2pt5gJZhUnOafLaTsLiCvrD7K6/8wa2FfViK4105y7mVGy6k9Dgnb6HqhWQPdHGkbDiBZMi6NkNYMe3LuJ6Qkd0mKt3VHpJDLU5RRxF1WO9FaX832ER37u9+JCoJnbu4BevMWlkdVNJxqC+vN5yxgNU73/txYMwr52kRJXtcMt1PKMw=
  repository: https://upload.pypi.org/legacy
  skip_cleanup: true
  on:
    python: '3.10'
    tags: true