language: python

dist: xenial

cache: pip

before_install:
- npm install npm@latest -g
- sudo apt-get update
- sudo apt-get install pandoc
- pip install pypandoc

install:
- pip install tox-travis

# before_script:
# - 'openssl aes-256-cbc -K $my_key -iv $my_iv -in myservice.env.enc -out myservice.env -d || true'

script: tox

jobs:
  include:
    - stage: Run tox tests
      python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - stage: Run system test with template
      script: 
        - git clone git@github.ibm.com:CloudEngineering/sdkgen-systest.git
        - cd sdkgen-systest
        - ./install_scripts/install_deps_ubuntu.sh
        - ./setup_and_generate.sh -l ibm-python -t $TRAVIS_BRANCH

before_deploy:
- pip install bump2version
- nvm install 12
- npm install @semantic-release/changelog
- npm install @semantic-release/exec
- npm install @semantic-release/git
- npm install @semantic-release/github

# deploy:
# - provider: script
#   script: npx semantic-release
#   skip_cleanup: true
#   on:
#     python: '3.5'
#     branch: master
# - provider: pypi
#   user: __token__
#   password: $PYPI_TOKEN
#   repository: https://upload.pypi.org/legacy
#   skip_cleanup: true
#   on:
#     python: '3.5'
#     tags: true
